/**
 *
 *  Sessions.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace stend
{

class Sessions
{
  public:
    struct Cols
    {
        static const std::string _sessionid;
        static const std::string _userid;
        static const std::string _refreshkeyhash;
        static const std::string _refreshkeysalt;
        static const std::string _expirydate;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Sessions(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Sessions(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Sessions(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Sessions() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column sessionid  */
    ///Get the value of the column sessionid, returns the default value if the column is null
    const int64_t &getValueOfSessionid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getSessionid() const noexcept;
    ///Set the value of the column sessionid
    void setSessionid(const int64_t &pSessionid) noexcept;

    /**  For column userid  */
    ///Get the value of the column userid, returns the default value if the column is null
    const int64_t &getValueOfUserid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getUserid() const noexcept;
    ///Set the value of the column userid
    void setUserid(const int64_t &pUserid) noexcept;

    /**  For column refreshkeyhash  */
    ///Get the value of the column refreshkeyhash, returns the default value if the column is null
    const std::vector<char> &getValueOfRefreshkeyhash() const noexcept;
    ///Return the column value by std::string with binary data
    std::string getValueOfRefreshkeyhashAsString() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::vector<char>> &getRefreshkeyhash() const noexcept;
    ///Set the value of the column refreshkeyhash
    void setRefreshkeyhash(const std::vector<char> &pRefreshkeyhash) noexcept;
    void setRefreshkeyhash(const std::string &pRefreshkeyhash) noexcept;

    /**  For column refreshkeysalt  */
    ///Get the value of the column refreshkeysalt, returns the default value if the column is null
    const std::vector<char> &getValueOfRefreshkeysalt() const noexcept;
    ///Return the column value by std::string with binary data
    std::string getValueOfRefreshkeysaltAsString() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::vector<char>> &getRefreshkeysalt() const noexcept;
    ///Set the value of the column refreshkeysalt
    void setRefreshkeysalt(const std::vector<char> &pRefreshkeysalt) noexcept;
    void setRefreshkeysalt(const std::string &pRefreshkeysalt) noexcept;

    /**  For column expirydate  */
    ///Get the value of the column expirydate, returns the default value if the column is null
    const ::trantor::Date &getValueOfExpirydate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getExpirydate() const noexcept;
    ///Set the value of the column expirydate
    void setExpirydate(const ::trantor::Date &pExpirydate) noexcept;


    static size_t getColumnNumber() noexcept {  return 5;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Sessions>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Sessions>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> sessionid_;
    std::shared_ptr<int64_t> userid_;
    std::shared_ptr<std::vector<char>> refreshkeyhash_;
    std::shared_ptr<std::vector<char>> refreshkeysalt_;
    std::shared_ptr<::trantor::Date> expirydate_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[5]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where sessionid = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where sessionid = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "sessionid,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "userid,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "refreshkeyhash,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "refreshkeysalt,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "expirydate,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace stend
} // namespace drogon_model
